const { model, Schema } = require("mongoose");

const userSchema = new Schema(
  {
    name: { type: String },
    phone: { type: String, required: true },
    accounts: [
      {
        name: String,
        status: String,
        message: String,
        resp_date: Date,
      },
    ],
    refArr: [
      {
        name: String,
        date: Date,
      },
    ],
    businessName: { type: String },
    doesFileITR: { type: String },
    doesFileGST: { type: String },
    businessType: { type: String },
    agent_id: {
      type: String,
      unique: true,
      required: true,
    },
    salaryMode: { type: String },
    bankName: { type: String },
    SalaryType: { type: String },
    CompanyName: { type: String },
    UserPostion: { type: String },
    CompanyAddress: { type: String },
    CompleteAddress: { type: String },
    salarySlip: { type: String },
    aadhar: { type: String },
    dob: { type: String },
    loanAmount: { type: String },
    email: { type: String },
    addr: { type: String },
    pan: { type: String },
    city: { type: String },
    state: { type: String },
    gender: { type: String },
    employment: { type: String },
    company_name: { type: String },
    income: { type: String },
    partner: { type: String, default: "None" },
    partnerHistory: [
      {
        name: { type: String, required: true },
        date: { type: Date, default: Date.now },
        type: { type: String, enum: ["new", "dedupe"], required: true },
      },
    ],
    partnerSent: { type: Boolean },
    residence_type: { type: String },
    phoneOtp: { type: String, length: 4 },
    pincode: { type: String, length: 6 },
    phoneOtpExpire: { type: Date },
    eformFilled: { type: Boolean, default: false },
    isBanned: { type: Boolean, default: false },
    consentData: { date: { type: String }, ip: { type: String } },
    consent: { type: String },
    accountDeleted: { type: Boolean },
    business_details: {
      company_type: { type: String },
      business_name: { type: String },
      business_age: { type: String },
      annual_turnover: { type: String },
      gstRegistered: { type: Boolean },
      currentAccount: { type: Boolean },
    },
  },
  { timestamps: true, strict: false },
);

module.exports = model("webUserDB", userSchema);
